### ISSUE TITLE
dosent show up on the magic mirror

### ISSUE THREAD

**Issue by Eburkis** [boghammar/MMM-SL-PublicTransport#13]
dont know whats wrong but it seems that the magic mirror dosent load the MMM-SL-PublicTransport at all

**Comment by boghammar** [comment]
Please send your configuration and maybe I can see what's wrong

**Comment by Eburkis** [comment]
it does not work when i have "position" on Top-right and only works on "middle-center" "and bottom_left" 
it does not show up in top_right

`{
        module: "MMM-SL-PublicTransport",
        position: "bottom_left",
        header: "Bussar",
        config: {
            apikey: "965b69b5a6774443bbcb16f93c2ab60d",         // REQUIRED.
            stationid: "2023",   // REQUIRED. You need to run the utility findStation to get this
            stationname: "Rudboda Torg",            // This is the name of the station. It's shown in the header if you have set a header on the module
            direction: 1,                   // Optional, if set only show departures in that direction. Not implemented yet
            //displaycount: 100,              // Optional, show this number of departures. Not implemented yet
            //lines: [],                      // Optional, only show the lines listed in the array. Not implemented yet
            //showdisturbances: false,        // Not implemented yet
            fade: true,
            fadePoint: 0.3,
			}
        }, `

**Comment by boghammar** [comment]
As far as I can see your config looks ok.

If it shows up or not depending on position my conclusion is that its not a problem with the module code, it must be something in your configuration, strange ... 
Please check the logs in your browser console and the MM logs to see if you get any clue why it does not show up in a particular location.

I had lots of trouble until I noticed that the position parameters always use an underscore '_' instead of a dash '-' i.e. top_right instead of top-right. Json is also very sensitive to missing commas ',' and things like that.

**Comment by Eburkis** [comment]
now it works but just in some positiones and now it is not always showing the busses in order(time) 
 like here, dont know why it does that
https://imgur.com/npbT6JD
https://imgur.com/NIxkWEU

**Comment by boghammar** [comment]
Strange with the position problem. As I said that is nothing that is controlled by the module, it's MM itself that places the modules on the screen.

About the ordering issue, I have to look at it later when I get the time, if you have knowledge in developing Javascript applications you are free to try to find a solution and send in a patch. My "station", Erikslund in Täby :) ,  only have 2 buss lines and I did not see it when developing. When I get the time I will try with your station and see what I get from the SL API.

**Comment by boghammar** [comment]
I'm closing this issue since its about the module not showing up and it does. The ordering issue is captured in another issue [Sort order is sometimes wrong](https://github.com/boghammar/MMM-SL-PublicTransport/issues/14)
