### ISSUE TITLE
Will not render

### ISSUE THREAD

**Issue by Pliind** [boghammar/MMM-SL-PublicTransport#17]
Ive done everything after the books, i see that api-requests are being excecuted. But my display shows nothing. Ive validated the code, ive added only api and station, ive done it all, wont render on the screen..
all other modules i have work.

**Comment by boghammar** [comment]
Please provide your configuration file so that I can have a look at it.

**Comment by Pliind** [comment]
/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "en",
	timeFormat: 24,
	units: "metric",
	zoom: "1.0",
	modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "xxxx",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check-o ",
						url: "https://xxxxxx.com/?export",
						auth: {
			    user: "xxxx",
			    pass: "xxxxx",
			    method: "basic"
			}
					}
				]
			}
		},
		{
    module: 'MMM-LICE',
    position: 'bottom_right',                   // Best in left, center, or right regions
    config: { 
		accessKey: "xxxxxx", // Free account & API Access Key at currencylayer.com
		source: "SEK",       // The source currency
		x1: "USD",
		x2: "EUR",
		x3: "GBP",
		x4: "DKK",
		useHeader: false,                 
		header: "Show me the money",
		maxWidth: "400px",
    }
},
		{
			module: "currentweather",
			position: "top_right",
			zoom: "5.0",
			config: {
				location: "Solna",
				locationID: "2675397",  //ID from http://www.openweathermap.org/help/city_list.txt
				appid: "xxxxx"
			}
		},
		{
			module: "weatherforecast",
			position: "top_right",
			header: "Weather Forecast",
			config: {
				location: "Solna",
				locationID: "2675397",  //ID from http://www.openweathermap.org/help/city_list.txt
				appid: "xxxxx"
			}
		},
		{
        module: 'MMM-SL-PublicTransport',
        position: 'top-center',
        header: 'Busses',
        config: {
            apikey: 'your-api-key',         // REQUIRED.
            stationid: '3434',   // REQUIRED. You need to run the utility findStation to get this
            stationname: 'Bergshamra Gård',            // This is the name of the station. 
                                            // It's shown in the header if you have set a header on the module
            direction: 1,                   // Optional, if set only show departures in that direction.
                                            // Direction is either 1 or 2, test to see which one you need.
            displaycount: 10,               // Optional, show this number of departures for each direction.
            lines: [],                      // Optional, only show the lines listed in the array. 
                                            // This can be a simple array of strings like ['611', '312', '629'] or 
                                            // a combination of objects with linename and direction
                                            // like [['611', 1], '312', ['629', 2]]. 
                                            // This second variant can only be used when direction has a value
                                            // See the description on "in to town" functionality below.  
            showdisturbances: false,        // Not implemented yet
            fade: true,                     // Shall the table of departures be faded or not
            fadePoint: 0.2,                 // Fraction from end where to start fading
            updateInterval: 5*60*100,       // Number of milliseconds between calls to Trafiklab's API
                                            // There are limitations on number of calls per minute and month
            uiUpdateInterval: 1000,         // Number of milliseconds between updates of the departure list 
            SSL: false,                     // Use https to access the TrafikLab services, defaults to
                                            // false since I have experienced problems accessing this 
                                            // service over https. Have an ongoing discussion with 
                                            // TrafikLab
            debug: false,                   // Enable some extra output when debugging
        }
    },
		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "Sweclockers",
						url: "https://www.sweclockers.com/feeds/nyheter"
					}
				],
				showSourceTitle: true,
				showPublishDate: true
			}
		},
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Comment by Pliind** [comment]
all modules above render except the publictransport one

**Comment by boghammar** [comment]
Please change the line
   position: 'top-center',
to
  position: 'top_center',
for the SL-module

Use an underscore instead of a dash

Regards

**Comment by boghammar** [comment]
I have changed the faulty example in the readme.md that was using a dash so that no one else falls in this trap :)

Sorry about that.

**Comment by Pliind** [comment]
Phew, thanks thought i was going insane there for a while :)

**Comment by boghammar** [comment]
My bad with the misleading configuration example. Closing this issue now.
