### ISSUE TITLE
Both directions on same line

### ISSUE THREAD

**Issue by AlCurrent** [boghammar/MMM-SL-PublicTransport#29]
Hi, I tried to manage a workaround for this. Anything you can recommend to do to achieve this or can this be a future feature?

I need both directions for 1 line. Tried duplicating the module and make a "MMM-SL-PublicTransport2" but it does not seem to work. However, I can see it gets 2 lists in the log, but only shows one of them:

MMM-SL-PublicTransport: Found 12 DEPARTURES for station id=1603                                                                 MMM-SL-PublicTransport: Found 10 DEPARTURES for station id=1605 

Thanks.

**Comment by boghammar** [comment]
Have opened Issue #32 that will handle this.
