### ISSUE TITLE
per station "lines" config

### ISSUE THREAD

**Issue by jo89lin** [boghammar/MMM-SL-PublicTransport#31]
Thanks for a great module! I one one issue with my current config.

I have two stations where two lines (B and C) pass with 1 min delay. But i want to show both stations since I use both. But my MM now shows duplicates in both directions for lines B and C. 

For station X show lines "A" (but hide B and C)
For station Y show lines ["B", 2], "C" 

So If i need to take A, I walk to X. But for B and C I always get on at station Y Since it is closer. A does not depart from Y.

So if I could configure a lines filter per station that would solve it.

**Comment by boghammar** [comment]
Thanks, nice that it's appreciated.

I have had thoughts around a lines filter but never got around to it. It will probably require some serious redesign but I will have a look at it. Could you please provide an example config where the problem occurs.

**Comment by boghammar** [comment]
Have opened Issue #32 that will handle this.
