### ISSUE TITLE
Not possible to show lines ending with a letter

### ISSUE THREAD

**Issue by JcbSndstrm** [boghammar/MMM-SL-PublicTransport#35]
Some lines have the letter x in their ending, for example 43X Kallhäll – Nynäshamn. Somehow it seems like they can not be included in lines.

**Comment by boghammar** [comment]
Hi

please send the configuration that you are trying and I'll check what's happening. 

Maybe this is something that @Samtrafiken can help out with; is there some special handling of ..X departures that I need to take into account?

**Comment by JcbSndstrm** [comment]
I'm sorry for the late reply. This is the configuration I use. 

{
    module: 'MMM-SL-PublicTransport',
        position: 'top_right',
        	header: 'Avgångar',
		config: {
		fade: false,
			apikey: 'xxxxx', 
			stations: [
			{
			stationId: 9325, 
						stationName: 'Sundbybergs station',
					lines: [
				{
					line: 10,
				swapDir: false
			},
			{
				line: 22,
				swapDir: false
			},
			{
				line: 43,
				swapDir: true
			}
			]
			}
		],
		displaycounts: 6,
		showdisturbances: true,
		showIcon: false
		}
},

No departures of 43X trains shows up in the module and the config becomes unable to read if I add the line 43X like this:
line: 43X,
swapDir: true

**Comment by boghammar** [comment]
I'm afraid its the old 'uppercase/lowercase" issue. 
It has to be an uppercase 'x'
This is a screenshot
![image](https://user-images.githubusercontent.com/10381934/81329739-492b5d80-909f-11ea-8518-094bcd9d02f6.png)
when using this configuration
{
	stationId: 1080,
	stationName: 'Stockholm City',
	excludeTransportTypes: ['Bus', 'Metro'],
	lines: [
		{line: '42X'},
		{line: 43},						
	]
}

I will have to introduce a type check and if its a string equalize the case of the strings to do a comparison.

**Comment by boghammar** [comment]
Note that if you specify the lines option you have to specify both the 43 and the 43X lines like this
lines: [
   {line: '43X'},
   {line: 43},
]

**Comment by boghammar** [comment]
Now it should handle case problems but you still need to specify the 'letterlines' as strings.
